### ISSUE TITLE
'com.jcraft.jsch.JSchException: Auth fail' when trying to connect repeately.

### ISSUE THREAD

**Issue by PalrajJayarajBosch** [mwiede/jsch#255] opened 2022-12-09 08:31 UTC
Hello I have a project, where we connect to the a device using JSCH, version-0.1.55. There are N (around 100) number of commands to be run. Some commands take around 10-20 minutes to complete.
Hence, we have designed the application to disconnect and connect after each and every command.

It is working fine for around 70-80 steps and then it throws exception that com.jcraft.jsch.JSchException: Session.connect: java.io.IOException: End of IO Stream Read
```

private synchronized Session connect(final ServerConfiguration configuration) throws JSchException {
    LOGGER.info("ServerConnection.connect: " + configuration);
    JSch jsch = new JSch();
    if (null != configuration.getKeyFile()) {
      jsch.addIdentity(configuration.getKeyFile().getAbsolutePath(), configuration.getPassword());
    }
    Session localSession =
        jsch.getSession(configuration.getUsername().trim(), configuration.getIp().trim(), configuration.getPort());
    if (!isTrivial(configuration.getPassword())) {
      localSession.setPassword(configuration.getPassword());
    }
    Properties config = new Properties();
    config.put("PreferredAuthentications", "publickey,keyboard-interactive,password");
    config.put("StrictHostKeyChecking", "no");
    localSession.setConfig(config);
    localSession.connect();
    LOGGER.info("ServerConnection.connect: connection successful.");
    return localSession;
  }

public synchronized void disconnectCurrentSession() {
    LOGGER.info("ServerConnection.disconnectCurrentSession: started disconnecting");
    if (this.session.isConnected()) {
      this.session.disconnect();
    }
    LOGGER.info("ServerConnection.disconnectCurrentSession: completed disconnecting");
  }
```

The log file when it is fails is
```Connecting to <IpAddress> port 22 At : com.jcraft.jsch.Session.connect(Session.java:204)
Connection established At : com.jcraft.jsch.Session.connect(Session.java:245)
Remote version string: SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2+rpt1 At : com.jcraft.jsch.Session.connect(Session.java:301)
Local version string: SSH-2.0-JSCH-0.1.54 At : com.jcraft.jsch.Session.connect(Session.java:303)
CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256 At : com.jcraft.jsch.Session.checkCiphers(Session.java:2461)
CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521 At : com.jcraft.jsch.Session.checkKexes(Session.java:2512)
CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521 At : com.jcraft.jsch.Session.checkSignatures(Session.java:2553)
SSH_MSG_KEXINIT sent At : com.jcraft.jsch.Session.send_kexinit(Session.java:694)
SSH_MSG_KEXINIT received At : com.jcraft.jsch.Session.connect(Session.java:316)
kex: server: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1 At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:99)
kex: server: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:99)
kex: server: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:99)
kex: server: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:99)
kex: server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:99)
kex: server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:99)
kex: server: none,zlib@openssh.com At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:99)
kex: server: none,zlib@openssh.com At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:99)
kex: server:  At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:99)
kex: server:  At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:99)
kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:103)
kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521 At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:103)
kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:103)
kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:103)
kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96 At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:103)
kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96 At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:103)
kex: client: none At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:103)
kex: client: none At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:103)
kex: client:  At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:103)
kex: client:  At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:103)
kex: server->client aes128-ctr hmac-sha1 none At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:145)
kex: client->server aes128-ctr hmac-sha1 none At : com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:150)
SSH_MSG_KEX_ECDH_INIT sent At : com.jcraft.jsch.DHECN.init(DHECN.java:99)
expecting SSH_MSG_KEX_ECDH_REPLY At : com.jcraft.jsch.DHECN.init(DHECN.java:101)
ssh_rsa_verify: signature true At : com.jcraft.jsch.KeyExchange.verify(KeyExchange.java:229)
Permanently added '<IpAddress>' (RSA) to the list of known hosts. At : com.jcraft.jsch.Session.checkHost(Session.java:846)
SSH_MSG_NEWKEYS sent At : com.jcraft.jsch.Session.send_newkeys(Session.java:706)
SSH_MSG_NEWKEYS received At : com.jcraft.jsch.Session.connect(Session.java:363)
SSH_MSG_SERVICE_REQUEST sent At : com.jcraft.jsch.UserAuthNone.start(UserAuthNone.java:49)
SSH_MSG_SERVICE_ACCEPT received At : com.jcraft.jsch.UserAuthNone.start(UserAuthNone.java:62)
Authentications that can continue: publickey,keyboard-interactive,password At : com.jcraft.jsch.Session.connect(Session.java:446)
Next authentication method: publickey At : com.jcraft.jsch.Session.connect(Session.java:448)
an exception during authentication
java.io.IOException: End of IO Stream Read At : com.jcraft.jsch.Session.connect(Session.java:500)
Disconnecting from <IpAddress> port 22 At : com.jcraft.jsch.Session.disconnect(Session.java:1721)
Auth fail At : Executor.execute(Executor.java:29)
com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:519)
	at com.jcraft.jsch.Session.connect(Session.java:183)```

Could you please let me know, how to resolve this issue?

Thanks,
Palraj

**Comment by mwiede** [comment] 2022-12-09 10:53
closing as duplicate of https://stackoverflow.com/questions/74741751/com-jcraft-jsch-jschexception-auth-fail-when-trying-to-connect-repeately

**Closed by mwiede** 2022-12-09 10:53 UTC
